### ISSUE TITLE
Foundation 5 foreground orbit overlap showing next slide

### ISSUE THREAD

**Issue by CJTharp** [thingles/foreground#280] opened 2016-01-19 00:42 UTC
New Foreground Foundation Five Orbit Slider shows next slide:

Site with Foreground Foundation 4:

![old foreground foundation](https://cloud.githubusercontent.com/assets/9703601/12406427/c5a590e4-be01-11e5-921e-a7b75f9279c7.png)

Site with Foreground Foundation 5 (see far left of picture):
![new foreground foundation](https://cloud.githubusercontent.com/assets/9703601/12406432/d373d172-be01-11e5-8db4-42f6a95c0558.png)

More than likely a minor css issue, but so far I can't find it.

**Comment by Hutchy68** [comment] 2017-04-17 18:39
I know quite old, but is this still an issue. I can't reproduce it.

**Comment by Hutchy68** [comment] 2017-04-18 16:03
Found it, see #193. Closing this issue.

**Closed by Hutchy68** 2017-04-18 16:03 UTC
Labels: bug
