### ISSUE TITLE
h3 larger than h2 in small screen

### ISSUE THREAD

**Issue by dram** [thingles/foreground#69] opened 2014-01-24 03:03 UTC
h3 is a bit too larger in small screen.

**Comment by kghbln** [comment] 2015-01-27 14:48
This is still in version 1.1 and a bit obnoxious since it appears to stay sticky since overriding via CSS is not possible.

@Hutchy68 Do you have an idea to fluff this up?

**Comment by Hutchy68** [comment] 2015-01-27 14:55
I will take a look but probably won't be till later tonight.

**Comment by kghbln** [comment] 2015-01-27 15:04
No worries, take you time. I pinged you since this is a pretty visible thing and since you are an CSS expert. :)

**Comment by Hutchy68** [comment] 2015-01-28 17:21
Hmm, here is the offending CSS

```
.ns-subject h3,
.ns-special h3,
.page-Main_Page h3 {
  font-weight: bold;
  font-size: 2em;
}
```

What perplexes me is this...

```
h3 {
  font-weight: normal;
  font-size:1em;
}

which precedes it. ??? Doesn't make any sense because `.ns-subject` is going to be the majority of pages. `.ns-special` I could see, but it needs a min-width element to control size vs. screen's size.

https://github.com/thingles/foreground/commit/1d21181cac42f545ae906dee3628e2cdb505c7bc

Perhaps @garrickvanburen knows what the original issue was with the `<h3>` tags he was trying to fix. In meantime, I will try an install with them deleted and see what the affects are.

**Comment by kghbln** [comment] 2015-01-28 20:47
Great, thank you for digging into this! Perhaps it was just an in-the-heat-of-the-night-thing. :)

**Comment by Hutchy68** [comment] 2015-01-29 04:18
@thingles I just pushed it against the release/ branch for 1.x for now.

Appreciate it if someone can test it. Specifically with SMW, still scratching my head what SpecialPages have H3 headings.

**Comment by kghbln** [comment] 2015-01-29 21:45
If have asked someone who reported this to me to check whether it solves the issue or not. Hope to come back to you soon. Thanks again for having a look. Ad hoc I am not aware of any extension using h3 headings on special pages, but one never knows.

**Comment by kghbln** [comment] 2015-02-03 20:55
I got a positive feedback about the change, i.e. the issue is solved. Now h2 and h3 appear to be pretty similar, but this is a matter of adding CSS directly into the wiki I believe.

**Comment by Hutchy68** [comment] 2017-04-20 12:38
Wow, this was fixed but never closed. Closing now.

**Closed by Hutchy68** 2017-04-20 12:38 UTC
Labels: bug, CSS
