### ISSUE TITLE
On touch screen devices

### ISSUE THREAD

**Issue by paladox** [thingles/foreground#206] opened 2014-12-09 14:09 UTC
Hi it seems on the iPad and iPhone you can to press twice to get it to come up. For example when trying to click search bar you have to press it twice or when clicking actions. Please could someone fix that.

**Comment by ummahusla** [comment] 2015-04-01 09:19
The issue is still occurs, has anyone has an idea why it happens? 

To open post/article setting, you need to press twice, to view options..

**Comment by Hutchy68** [comment] 2015-04-01 20:24
It's the way touch devices handle events. Right now we use mouseenter and mouseleave. I've tried touchenter and touchleave still produces same result. iOS is a bit odd and actually delays the event from firing. I think you can eliminate the delay but as soon as you pick your finger up the menu will disappear again.  

The probably will be at won't fix.

**Comment by Hutchy68** [comment] 2015-12-28 19:07
That is default Foundation even with a on hover. Touch screens require a touch to focus, then a second touch activate.

**Closed by Hutchy68** 2015-12-28 19:07 UTC
