### ISSUE TITLE
Dropdown for Actions button 

### ISSUE THREAD

**Issue by Hutchy68** [thingles/foreground#243] opened 2015-12-08 14:35 UTC
There is a bug with the onHover over the actions button in the develop branch. I'm not sure where it worked its way into the dev branch but it is breaking onHover element for actions menu when used on a media screen < abt 790px. Yes, it is hard set with our foreground.js but in v1.1 it worked as expected. Not sure if something changed in Foundation's js. I think the develop branch pulled in the last version of Foundation 4.

@thingles Wikiapiary can be broken on small screens because you are using 1.2-alpha which came from the develop branch.

### Initial load
![rightafterload](https://cloud.githubusercontent.com/assets/3527469/11658036/798c3610-9d8e-11e5-92fc-1b1d06b312d9.jpg)

### After Click (touch devices) or Hover reduced Browser width
![afterclickorhover](https://cloud.githubusercontent.com/assets/3527469/11658037/7b0a1a48-9d8e-11e5-9375-cd3e9a9b9602.jpg)

**Comment by paladox** [comment] 2015-12-08 17:35
Fixed by https://github.com/thingles/foreground/pull/244

The problem was caused by https://github.com/thingles/foreground/commit/e5f8fbcb9f5475e87b178c0c601d038d384d7f25 

This piece of code 

<a href="#" class="button dropdown small secondary radius">

was the caused I fixed it with

<a href="#" data-dropdown="drop1" class="button dropdown small secondary radius">

Re added data-dropdown="drop1" which caused the problem when it was removed.

All tested now and the patch works.

**Closed** 2015-12-08 18:57 UTC
Labels: blocker, bug
